// Generated by https://quicktype.io

namespace swnbot.Classes
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class HeavyWeapons
    {
        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("Damage")]
        public string Damage { get; set; }

        [JsonProperty("Range")]
        public string Range { get; set; }

        [JsonProperty("Cost")]
        public int Cost { get; set; }

        [JsonProperty("Mag")]
        public string Mag { get; set; }

        [JsonProperty("Encumbrance")]
        public string Encumbrance { get; set; }

        [JsonProperty("Attribute")]
        public string Attribute { get; set; }

        [JsonProperty("TechLevel")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long TechLevel { get; set; }

        [JsonProperty("Id")]
        public long Id { get; set; }
    }

    public partial class HeavyWeapons
    {
        public static HeavyWeapons[] FromJson(string json) => JsonConvert.DeserializeObject<HeavyWeapons[]>(json, Converter.Settings);
    }

    public static class SerializeHeavyWeapons
    {
        public static string ToJson(this HeavyWeapons[] self) => JsonConvert.SerializeObject(self, Converter.Settings);
    }

    internal static class ConvertHeavyWeapons
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters = {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
